name: HEMS CI/CD pipeline 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -f ./Dockerfile -t nirminedh/homeenergymanagementsystemhems:latest .
          docker push nirminedh/homeenergymanagementsystemhems:latest

          
 deploy:

  name : deploy 
  needs: build
  runs-on: ubuntu-latest
  steps :
    - uses: actions/checkout@master
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

    
    - name: install minikube
      uses: medyagh/setup-minikube@master
      with:
          minikube-version: latest

    - name: Start Minikube
      run: |
          minikube start --driver=docker
       
    - name: Pull Docker image from Docker Hub
      env :
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |

          docker pull nirminedh/homeenergymanagementsystemhems:latest
        
          
    - name: Deploy to Minikube
      run: |
          kubectl apply -f homeenergymanagementsystem-deployment.yaml
          kubectl apply -f homeenergymanagementsystem-service.yaml
            
    - name: get events 
      run: |
    
        kubectl get events
